splitio/android-client

CHANGES.txt, build.gradle, src/main/java/io/split/android/client/cache/SplitChangeCache.java, src/main/java/io/split/android/engine/experiments/RefreshableSplitFetcher.java
Reported problem is that the cached storage might get corrupted. Adding extra defensive code so in case the cache cannot be parsed correctly, simply skip it rather than propagating the error.
I will keep investigating why the cache might be corrupted. But it is hard since it cannot be reproduced locally.
=> extra checks

CHANGES.txt, build.gradle, src/main/java/io/split/android/client/HttpMySegmentsFetcher.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/cache/IMySegmentsCache.java, src/main/java/io/split/android/client/cache/ISplitCache.java, src/main/java/io/split/android/client/cache/MySegmentsCache.java, src/main/java/io/split/android/client/cache/SplitCache.java, src/main/java/io/split/android/client/cache/SplitChangeCache.java, src/main/java/io/split/android/client/storage/FileStorage.java, src/main/java/io/split/android/client/storage/IStorage.java, src/main/java/io/split/android/client/storage/MemoryAndFileStorage.java, src/main/java/io/split/android/client/storage/MemoryStorage.java, src/main/java/io/split/android/client/utils/Utils.java, src/test/java/io/split/android/engine/segments/MySegmentsCacheTest.java, src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Update Split cache to save split cache on disk on app background
- Storing split cache in memory in native objects instead of json 
- Modified ISplitCache interface
- Updated SplitChangeCache to interact correctly with Split Cache
- Added unit test for Split Cache component
=> SDKS-320: Android Only store Splits in cache when going in background

build.gradle, src/main/java/io/split/android/client/SplitClientConfig.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/impressions/ImpressionsManager.java, src/main/java/io/split/android/client/impressions/ImpressionsStorageManager.java, src/main/java/io/split/android/client/impressions/ImpressionsStorageManagerConfig.java, src/main/java/io/split/android/client/impressions/StoredImpressions.java, src/test/java/io/split/android/client/impressions/ImpressionsManagerTest.java, src/test/java/io/split/android/engine/impressions/ImpressionsStorageTest.java
- Storing impressions in memory instead of saving to disk when generated
- Saving to disk when app goes to background or Split client is closed
- Added unit tests to ImpressionsStorageManager component
=> SDKS-316: Android Only store Impressions in cache when going in background

CHANGES.txt, src/main/java/io/split/android/client/storage/splits/SqLitePersistentSplitsStorage.java
Some defensive code to avoid issues when deleting splits. Splits array to deleted partitioned y smaller arrays to avoid to many sqlite bind variable error when running delete statement.
=> Avoid big binding when delete

src/main/java/io/split/android/client/storage/db/EventDao.java, src/main/java/io/split/android/client/storage/db/GeneralInfoDao.java, src/main/java/io/split/android/client/storage/db/ImpressionDao.java, src/main/java/io/split/android/client/storage/db/MySegmentDao.java, src/main/java/io/split/android/client/storage/db/SplitDao.java
Solving [this](https://github.com/splitio/android-client/issues/222#issue-784764130) issue with add @Transaction to handle big query 
- added @Transaction on each @Query Room method
As  written in [doc](https://developer.android.com/reference/androidx/room/Transaction) : Room will only perform at most one transaction at a time, additional transactions are queued and executed on a first come, first serve order.
=> Add @Transaction on every @Query Room method

src/main/java/io/split/android/client/storage/attributes/AttributesStorageImpl.java, src/test/java/io/split/android/client/storage/attributes/AttributesStorageImplTest.java
Changed behavior in `set(Map<String, Object> attributes)` method in attributes storage. It should add / update values instead of clearing and reseting.
=> Modify set method behaviour in attributes storage

CHANGES.txt, build.gradle, src/main/java/io/split/android/client/network/SdkTargetPath.java, src/test/java/io/split/android/client/network/SdkTargetPathTest.java
- Modified encoding for user key when building path segment for `mySegments` request.
- Added tests.
=> [SDKS-5325] Replace key encoding for segments path

src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentsV2PayloadDecoder.java, src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java, src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessor.java, src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorConfiguration.java, src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorFactory.java, src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorFactoryImpl.java, src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorImpl.java, src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorker.java, src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java, src/test/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorImplTest.java
Created `MySegmentsNotificationProcessor` to process segments related notifications. These will be registered in the main `NotificationProcessor`.
`NotificationProcessor` continues to handle all types; when receiving a segments notification, it delegates to all registered `MySegmentNotificationProcessor` instances.
=> Notification Processor for MySegments

build.gradle, src/main/java/io/split/android/client/dtos/Event.java
- Removed `sizeInBytes` field from Events DTO.
=> Remove sizeInBytes field from serialization in EventDTO

src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/attributes/AttributesManagerFactory.java, src/main/java/io/split/android/client/attributes/AttributesManagerFactoryImpl.java, src/main/java/io/split/android/client/attributes/AttributesManagerImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java, src/main/java/io/split/android/client/service/attributes/AttributeTaskFactory.java, src/main/java/io/split/android/client/service/attributes/AttributeTaskFactoryImpl.java, src/main/java/io/split/android/client/service/attributes/ClearAttributesInPersistentStorageTask.java, src/main/java/io/split/android/client/service/attributes/LoadAttributesTask.java, src/main/java/io/split/android/client/service/attributes/UpdateAttributesInPersistentStorageTask.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java, src/main/java/io/split/android/client/storage/SplitStorageContainer.java, src/main/java/io/split/android/client/storage/attributes/AttributesStorageContainer.java, src/main/java/io/split/android/client/storage/attributes/AttributesStorageContainerImpl.java, src/main/java/io/split/android/client/storage/attributes/PersistentAttributesStorage.java, src/main/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorage.java, src/main/java/io/split/android/client/storage/db/StorageFactory.java, src/test/java/io/split/android/client/service/attributes/ClearAttributesInPersistentStorageTaskTest.java, src/test/java/io/split/android/client/service/attributes/LoadAttributesTaskTest.java, src/test/java/io/split/android/client/service/attributes/UpdateAttributesInPersistentStorageTaskTest.java, src/test/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorageTest.java
- Modified Attributes storage to enable one storage and one manager instance per client.
- Added user key in `PersistentAttributesStorage` methods.
- Moved creation of attributes loading task to `AttributeTaskFactory`.
=> Multiple attribute storages

src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java, src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerRegistryImpl.java, src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java, src/test/java/io/split/android/client/service/SynchronizerTest.java, src/test/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerRegistryImplTest.java, src/test/java/io/split/android/client/service/telemetry/SynchronizerImplTelemetryTest.java
Trigger attributes loading after a new client is created, if needed.
=> Dynamically load attributes from cache when a new client is created

src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentsPayloadDecoder.java, src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentsV2PayloadDecoder.java, src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java, src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java, src/test/java/android/util/Base64.java, src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java, src/test/java/io/split/android/client/service/sseclient/notifications/MySegmentsPayloadDecoderTest.java
Delegate notification processing to corresponding `MySegmentsNotificationProcessor` instance.
This is done by replicating a portion of the encoded string that's present in the channel property of the notification and comparing against each registered processor.
=> Delegate notification processing to corresponding MySegmentsNotificationProcessor

build.gradle, src/main/java/io/split/android/client/SplitFactory.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java, src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- Added convenience methods for client retrieval in `SplitFactory`.
- Deprecated `isReady()` method in `SplitFactory`.
- Fixed bug in `MySegmentsNotificationProcessor` registration.
=> Modify SplitFactory methods

src/androidTest/java/tests/integration/TrackTest.java, src/main/java/io/split/android/client/dtos/Event.java, src/main/java/io/split/android/client/dtos/SerializableEvent.java, src/main/java/io/split/android/client/utils/Json.java, src/main/java/io/split/android/client/utils/deserializer/EventDeserializer.java, src/main/java/io/split/android/client/utils/serializer/DoubleSerializer.java, src/test/java/io/split/android/client/service/events/EventsRequestBodySerializerTest.java, src/test/java/io/split/android/client/utils/JsonTest.java, src/test/java/io/split/android/client/utils/deserializer/EventDeserializerTest.java
- Added `Gson` deserializer for Events to prevent `Gson` from assuming a value is a `Double`, and expressing the value in scientific notation.
- Added `Gson` serializer for `Double` to prevent whole numbers to appear as fractions (i.e. `0` instead of `0.0`), matching the behavior to that of the Java SDK.
=> Events json deserializer

src/androidTest/java/tests/integration/SplitChangesCdnBypassTest.java, src/androidTest/java/tests/integration/SplitChangesTest.java, src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java, src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java
Add `till` query parameter to `splitChanges` request to bypass CDN.
=> Bypass CDN in splits

src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysTracker.java, src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysTrackerImpl.java, src/test/java/io/split/android/client/service/impressions/unique/UniqueKeysTrackerImplTest.java
- Added `UniqueKeysTracker` implementation which uses a `ConcurrentHashMap` to keep track of MTKs per userKey.
=> UniqueKeysTracker implementation

src/androidTest/java/tests/integration/streaming/ImpressionsCountTest.java, src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java, src/main/java/io/split/android/client/service/impressions/ImpressionsObserver.java, src/test/java/io/split/android/client/service/ImpressionsObserverTest.java, src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java
- Prevent impression count to be increased if calculated previous time is null or 0.
=> Avoid impression count with non existing previous time

build.gradle, src/androidTest/java/tests/integration/SingleSyncTest.java, src/main/java/io/split/android/client/SplitClientConfig.java, src/main/java/io/split/android/client/lifecycle/SplitLifecycleManagerImpl.java, src/main/java/io/split/android/client/service/executor/SplitTaskExecutorImpl.java, src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java, src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeyEntity.java, src/main/java/io/split/android/engine/scheduler/PausableScheduledThreadPoolExecutorImpl.java, src/main/res/values/strings.xml, src/test/java/io/split/android/client/service/SplitTaskExecutorTest.java, src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java, src/test/java/io/split/android/engine/scheduler/PausableScheduledThreadPoolExecutorImplTest.java
- Added a policy in the pausable task executor to prevent exceptions from being raised if tasks are submitted after the executor has been shut down.
- Added additional tests.
=> Policy for task executor

build.gradle, src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java, src/main/java/io/split/android/client/service/impressions/strategy/NoneStrategy.java, src/main/java/io/split/android/client/service/impressions/strategy/ProcessStrategy.java, src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysTracker.java, src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysTrackerImpl.java, src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java, src/test/java/io/split/android/client/service/impressions/ImpressionManagerRetryTimerProviderImplTest.kt, src/test/java/io/split/android/client/service/impressions/strategy/NoneStrategyTest.kt
- Added `ProcessStrategy` interface. The `apply` method receives only one `Impression` since it's what makes the most sense in this SDK.
- Created the `NoneStrategy`.
=> None strategy

build.gradle, src/androidTest/java/helper/IntegrationHelper.java, src/androidTest/java/helper/TestableSplitConfigBuilder.java, src/androidTest/java/tests/integration/InitialChangeNumberTest.java, src/androidTest/java/tests/integration/IntegrationTest.java, src/androidTest/java/tests/integration/SplitFetchSpecificSplitTest.java, src/androidTest/java/tests/integration/shared/BaseSharedClientsTest.java, src/androidTest/java/tests/integration/shared/SharedClientsIntegrationTest.java, src/androidTest/java/tests/integration/streaming/CleanUpDatabaseTest.java, src/androidTest/java/tests/integration/streaming/SseAuthFail4xxTest.java, src/androidTest/java/tests/service/EventsRequestTest.java, src/androidTest/java/tests/service/UniqueKeysIntegrationTest.java, src/main/java/io/split/android/client/SplitClientConfig.java, src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeyEntity.java, src/test/java/io/split/android/client/SplitClientConfigTest.java, src/test/java/io/split/android/client/service/SynchronizerTest.java, src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java
- Removed unused and deprecated methods from `SplitClientConfig`.
**Removed:**
```
public int numThreadsForSegmentFetch()
public int metricsRefreshRate()
public boolean debugEnabled()
public int waitBeforeShutdown()
public int authRetryBackoffBase()
public int streamingReconnectBackoffBase()
public int uniqueKeysRefreshRate()
public void set_impressionsChunkSize(long _impressionsChunkSize)
public Builder metricsRefreshRate(int seconds)
public Builder enableDebug()
public Builder waitBeforeShutdown(int waitTime)
public Builder authRetryBackoffBase(int authRetryBackoffBase)
public Builder streamingReconnectBackoffBase(int streamingReconnectBackoffBase)
```
**Renamed:**
```
public Builder synchronizeInBackground(boolean synchronizeInBackground)
public Builder …
```
=> Config class cleanup

src/main/java/io/split/android/client/service/synchronizer/SyncGuardian.java, src/main/java/io/split/android/client/service/synchronizer/SyncGuardianImpl.java, src/test/java/io/split/android/client/service/synchronizer/SyncGuardianImplTest.java
- Added `SyncGuardian` component. This component determines whether a synchronization is needed based on config values and the time of the last successful synchronization.
=> Sync guardian

src/main/java/io/split/android/client/service/sseclient/notifications/SplitsChangeNotification.java, src/test/java/io/split/android/client/service/sseclient/sseclient/notifications/SplitsChangeNotificationTest.java
- Added `previousChangeNumber`, `data` and `compressionType` fields to `SplitsChangeNotification`.
=> New update notification fields

.github/workflows/deploy.yml, build.gradle, src/main/java/io/split/android/client/SplitManagerImpl.java, src/main/java/io/split/android/client/api/SplitView.java, src/main/java/io/split/android/client/dtos/Split.java, src/main/java/io/split/android/engine/experiments/ParsedSplit.java, src/main/java/io/split/android/engine/experiments/SplitParser.java, src/test/java/io/split/android/client/SplitManagerImplTest.java, src/test/java/io/split/android/engine/experiments/SplitParserTest.java, src/test/java/io/split/android/helpers/SplitHelper.java
- Added `sets` field to Split DTO.
- Added `sets` field to `SplitView`
=> Modify flags DTO & manager object

src/main/java/io/split/android/client/SplitFilter.java, src/main/java/io/split/android/client/validators/FlagSetsValidatorImpl.java, src/main/java/io/split/android/client/validators/SplitFilterValidator.java, src/test/java/io/split/android/client/validators/FlagSetsValidatorImplTest.java
- Added a new filter type for sets.
- Added the set validator.
=> Sets validator

src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/service/ServiceConstants.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/splits/FilterSplitsInCacheTask.java, src/main/java/io/split/android/client/service/splits/SplitChangeProcessor.java, src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java, src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java, src/main/java/io/split/android/client/service/workmanager/SplitsSyncWorker.java, src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java, src/test/java/io/split/android/engine/splits/SplitChangeProcessorTest.java
- Added configured sets to `SplitChangeProcessor` to process flag updates taking sets into account.
- Added changes to provide configured sets to the component in normal flows as well as background sync.
=> Process changes according to sets

src/androidTest/java/fake/SynchronizerSpyImpl.java, src/androidTest/java/tests/storage/LoadSplitTaskTest.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java, src/main/java/io/split/android/client/localhost/LocalhostSynchronizer.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/splits/LoadSplitsTask.java, src/main/java/io/split/android/client/service/synchronizer/FeatureFlagsSynchronizer.java, src/main/java/io/split/android/client/service/synchronizer/FeatureFlagsSynchronizerImpl.java, src/main/java/io/split/android/client/service/synchronizer/Synchronizer.java, src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java, src/main/java/io/split/android/client/storage/splits/SplitsStorageImpl.java, src/test/java/io/split/android/client/service/LoadSplitsTaskTest.java, src/test/java/io/split/android/client/service/SynchronizerTest.java, src/test/java/io/split/android/client/service/synchronizer/FeatureFlagsSynchronizerImplTest.java, src/test/java/io/split/android/client/service/telemetry/SynchronizerImplTelemetryTest.java
- Prevent `SDK_READY_FROM_CACHE` to be triggered when filter differs from previous initialization.
- Added the query string generated from the sync config to `LoadSplitsTask`:
-  If the filter is different from the one in storage, storage is cleared and the filter in storage is updated. Also in that case, the task will return error (to prevent `SDK_READY_FROM_CACHE` from being triggered).
- In `SplitsStorageImpl`, fixed missing update to the in memory query string.
- Removed unnecessary methods from `Synchronizer` & `FeatureFlagsSynchronizer` interfaces.
=> Clear cache on filter change

src/main/java/io/split/android/client/service/executor/SplitTaskExecutionInfo.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java, src/main/java/io/split/android/client/service/http/HttpGeneralException.java, src/main/java/io/split/android/client/service/http/HttpStatus.java, src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java, src/main/java/io/split/android/client/service/sseclient/sseclient/RetryBackoffCounterTimer.java, src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java, src/test/java/io/split/android/client/service/sseclient/sseclient/RetryBackoffCounterTimerTest.java
- Added flag to indicate that the task should not be retried when flags sync fails with a 414 http code.
- Added functionality in `RetryBackoffCounterTimer` to check whether the task has been configured to not be retried.
=> Prevent retry in specific tasks

src/main/java/io/split/android/client/AlwaysReturnControlSplitClient.java, src/main/java/io/split/android/client/SplitClientImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java, src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- Added calls to treatment manager in `LocalhostSplitClient` and `SplitClientImpl`.
- To avoid keeping a reference to `SplitsStorage` in the client, general exceptions for these methods are being handled in `TreatmentManagerImpl`.
=> Sets evaluation in clients

src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/SplitFilter.java, src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/telemetry/TelemetryTaskFactoryImpl.java, src/main/java/io/split/android/client/telemetry/model/Config.java, src/main/java/io/split/android/client/telemetry/storage/TelemetryConfigProviderImpl.java, src/main/java/io/split/android/client/validators/FlagSetsValidatorImpl.java, src/main/java/io/split/android/client/validators/SplitFilterValidator.java, src/test/java/io/split/android/client/telemetry/TelemetryConfigBodySerializerTest.java, src/test/java/io/split/android/client/telemetry/storage/TelemetryConfigProviderImplTest.java, src/test/java/io/split/android/client/validators/FlagSetsValidatorImplTest.java
- Added sets fields in config telemetry.
=> Sets config telemetry

src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java, src/main/java/io/split/android/client/service/ServiceConstants.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/splits/FeatureFlagProcessStrategy.java, src/main/java/io/split/android/client/service/splits/SplitChangeProcessor.java, src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java, src/main/java/io/split/android/client/service/workmanager/SplitsSyncWorker.java, src/test/java/io/split/android/client/service/splits/SplitChangeProcessorTest.java, src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java
- Added functionality to process split changes taking into account set or name filters.
=> By name filter in feature flag processor

src/main/java/io/split/android/client/FilterBuilder.java, src/main/java/io/split/android/client/FilterGrouper.java, src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/SplitFactoryImpl.java, src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/main/java/io/split/android/client/service/splits/SplitChangeProcessor.java, src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java, src/test/java/io/split/android/client/FilterGrouperTest.java, src/test/java/io/split/android/client/service/splits/SplitChangeProcessorTest.java, src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java
- Modified `FilterGrouper` to return a map.
=> Filter grouping refactor

src/main/java/io/split/android/client/service/splits/FeatureFlagProcessStrategy.java, src/main/java/io/split/android/client/service/splits/SplitChangeProcessor.java, src/test/java/io/split/android/client/service/splits/SplitChangeProcessorTest.java
- Added check to prevent tracking non configured sets in storage (if at least one set has been configured)
- Added check in case filter values are empty.
=> Functionality fixes

src/androidTest/java/tests/integration/telemetry/TelemetryIntegrationTest.java, src/main/java/io/split/android/client/SyncConfig.java, src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java, src/test/java/io/split/android/client/SyncConfigTest.java
- Fixed flag sets config telemetry.
- Added instrumented tests for stats & config telemetry related to flag sets.
=> Sets telemetry tests

src/main/java/io/split/android/client/FlagSetsFilterImpl.java, src/main/java/io/split/android/client/service/splits/FeatureFlagProcessStrategy.java, src/main/java/io/split/android/client/validators/FlagSetsValidatorImpl.java, src/main/java/io/split/android/client/validators/SplitFilterValidator.java, src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java, src/test/java/io/split/android/client/TreatmentManagerWithFlagSetsTest.java, src/test/java/io/split/android/client/service/splits/SplitChangeProcessorTest.java
- Used Guava's Sets.intersection method
- Started to return empty map as result of evaluations by flag sets performed when the client has been destroyed
- Stopped modifying the sets from stored feature flags
- Added warning logs displayed when evaluating with invalid sets
=> Post review changes

build.gradle, gradle.properties, src/androidTest/java/helper/TestableSplitConfigBuilder.java, src/main/java/io/split/android/client/SplitClientConfig.java, src/main/java/io/split/android/client/SplitFactoryHelper.java, src/test/java/io/split/android/client/SplitFactoryHelperTest.kt
- Add prefix config value
- Use prefix to generate DB name
=> Prefix config

build.gradle, gradle.properties, src/androidTest/java/helper/TestableSplitConfigBuilder.java, src/androidTest/java/tests/database/DatabaseInitializationTest.java, src/androidTest/java/tests/integration/sets/FlagSetsEvaluationTest.java, src/androidTest/java/tests/integration/sets/FlagSetsMultipleFactoryTest.java, src/main/java/io/split/android/client/FilterBuilder.java, src/main/java/io/split/android/client/SplitClientConfig.java, src/main/java/io/split/android/client/SplitFactoryHelper.java, src/main/java/io/split/android/client/utils/Utils.java, src/main/java/io/split/android/client/validators/PrefixValidator.java, src/main/java/io/split/android/client/validators/PrefixValidatorImpl.java, src/test/java/io/split/android/client/SplitClientConfigTest.java, src/test/java/io/split/android/client/SplitFactoryHelperTest.kt, src/test/java/io/split/android/client/validators/PrefixValidatorImplTest.java
- Added prefix configuration parameter
=> Prefix config parameter

src/main/java/io/split/android/client/network/AuthenticatedRequest.java, src/main/java/io/split/android/client/network/Authenticator.java, src/main/java/io/split/android/client/network/SplitAuthenticatedRequest.java, src/main/java/io/split/android/client/network/SplitAuthenticator.java, src/test/java/io/split/android/client/network/SplitAuthenticatorTest.java
- Created `SplitAuthenticator` related classes to eventually replace the `okhttp3.Authenticator` type from the `proxyAuthenticator` config parameter.
The `SplitAuthenticator` class may be extended to provide authentication logic.
=> SplitAuthenticator

src/main/java/io/split/android/client/network/OkHttpAuthenticator.java, src/test/java/io/split/android/client/network/OkHttpAuthenticatorTest.java
- Added `OkHttpAuthenticator` for internal use, which works as a bridge between the `SplitAuthenticator` and the underlying HTTP library (OkHttp).
=> Internal authenticator

.github/workflows/instrumented.yml
- Applying an update to the instrumented tests workflow since it is now [encouraged](https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners) to run `android-emulator-runner` in `ubuntu-latest` instead of `macos`.
=> Update instrumented tests workflow

.github/workflows/instrumented.yml, .github/workflows/test.yml, src/androidTest/java/io/split/android/client/service/impressions/observer/ListenableLruCacheTest.java, src/main/java/io/split/android/client/service/impressions/observer/ListenableLruCache.java
- Added extension of LRU cache that allows to set a listener to be informed of evictions.
=> LRU cache with listener

src/main/java/io/split/android/client/dtos/MatcherType.java, src/main/java/io/split/android/engine/experiments/SplitParser.java, src/main/java/io/split/android/engine/experiments/UnsupportedMatcherException.java, src/test/java/io/split/android/engine/experiments/UnsupportedMatcherSplitParserTest.java
- Added `UnsupportedMatcherException` for cases when the SDK doesn't know the matcher being parsed.
- When an `UnsupportedMatcherException` is caught, a default conditions list is used instead of the original one.
- (Unrelated) added `@SerializedName` annotation for extra safety when using minification.
=> Default conditions in SplitParser

build.gradle, spec.gradle, src/androidTest/java/helper/IntegrationHelper.java, src/androidTest/java/tests/integration/FlagsSpecInRequestTest.java, src/androidTest/java/tests/integration/InitialChangeNumberTest.java, src/androidTest/java/tests/integration/SplitFetchSpecificSplitTest.java, src/androidTest/java/tests/integration/SplitsTwoDifferentApiKeyTest.java, src/androidTest/java/tests/integration/sets/FlagSetsPollingTest.java, src/androidTest/java/tests/integration/streaming/SplitsKillProcessTest.java, src/androidTest/java/tests/integration/streaming/SplitsSyncProcessTest.java, src/main/java/io/split/android/client/network/URIBuilder.java, src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java, src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java, src/test/java/io/split/android/http/URIBuilderTest.java
- Added `spec.gradle` file with the flags spec value.
- Added flags spec query param to `splitChanges` request.
- Modified `URIBuilder` to honor query param order.
- Adapted instrumented tests.
=> Flags spec in request

build.gradle, src/main/java/io/split/android/client/service/http/HttpFetcherImpl.java, src/main/java/io/split/android/client/service/http/HttpSseAuthTokenFetcher.java, src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java, src/main/java/io/split/android/client/service/sseclient/sseclient/SseAuthenticator.java, src/test/java/io/split/android/client/service/HttpFetcherTest.java
- Modified `HttpFetcherImpl` to always place `till` query parameter at the end, in case it exists.
=> Params rearrangement
