splitio/android-client

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/cache/SplitChangeCache.java
- src/main/java/io/split/android/client/metrics/HttpMetrics.java
- Added defensive code when parsing fetched splits changes
- Fixed minor issue posting metrics
> SDKS-250 (Fixed): Crash fetching split changes

- build.gradle
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/test/java/io/split/android/client/SplitClientImplTest.java
- Fixed issue about traffic allocation
- Added test case to verify issue
> SDKS-345: Fixed issue about traffic allocation = 1

- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/validators/ApiKeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/EventValidatorImpl.java
- src/main/java/io/split/android/client/validators/KeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/SplitValidatorImpl.java
- src/test/java/io/split/android/client/validators/ApiKeyValidatorTest.java
- src/test/java/io/split/android/client/validators/EventValidatorTest.java
- src/test/java/io/split/android/client/validators/KeyValidatorTest.java
- src/test/java/io/split/android/client/validators/SplitNameValidatorTest.java
Some fixes related to names having several spaces and tests for that.
> Fixed issue with white spaces and added new tests for that

- build.gradle
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/main/java/io/split/android/client/storage/MemoryAndFileStorage.java
- src/main/java/io/split/android/client/utils/BCrypt.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/test/java/io/split/android/BCryptTest.java
- src/test/java/io/split/android/FolderForApiKeyTest.java
- Added function to create folder data name based on ApiKey using BCrypt hashing algorithm
- Creating files in a data folder named using previous function
- Added unit tests for data folder name generation function
> SDKS-468: Issue with Android SDK caching

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/dtos/Split.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/test/java/io/split/android/SplitConfigurationsParsingTests.java
- Added configurations field to Split model. 
- Added parsing tests
> SDKS-599: Storing dynamic configurations in Split

- build.gradle
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/dtos/Split.java
- src/main/java/io/split/android/engine/experiments/ParsedSplit.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/test/java/io/split/android/SplitConfigurationsParsingTests.java
- src/test/java/io/split/android/client/SplitClientImplTest.java
- src/test/java/io/split/android/client/SplitManagerImplTest.java
- src/test/java/io/split/android/engine/experiments/AChangePerCallSplitChangeFetcher.java
- src/test/java/io/split/android/engine/experiments/RefreshableSplitFetcherTest.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/helpers/SplitHelper.java
- Added configurations to split result on get treaments
- Updated tests
> SDKS-600: Dynamic configurations evaluator

- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/api/SplitView.java
- src/test/java/io/split/android/client/SplitManagerImplTest.java
- Added configs field to SplitView. Updated split parsing to fill configs field.
- Added configurations value to some split manager tests
> SDKS-603: Dynamic configurations for Split Manager

- build.gradle
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
> SDKS-687: Fixed impressions in get treaments / with config

- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/TrackClientImpl.java
- src/main/java/io/split/android/client/validators/ApiKeyValidator.java
- src/main/java/io/split/android/client/validators/ApiKeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/EventValidator.java
- src/main/java/io/split/android/client/validators/EventValidatorImpl.java
- src/main/java/io/split/android/client/validators/KeyValidator.java
- src/main/java/io/split/android/client/validators/KeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/SplitValidator.java
- src/main/java/io/split/android/client/validators/SplitValidatorImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/main/java/io/split/android/client/validators/ValidationErrorInfo.java
- src/main/java/io/split/android/client/validators/ValidationMessageLogger.java
- src/main/java/io/split/android/client/validators/ValidationMessageLoggerImpl.java
- src/test/java/io/split/android/client/validators/ApiKeyValidatorTest.java
- src/test/java/io/split/android/client/validators/EventValidatorTest.java
- src/test/java/io/split/android/client/validators/KeyValidatorTest.java
- src/test/java/io/split/android/client/validators/SplitNameValidatorTest.java
- Refactored to similar implementation than iOS
- Added more exhaustive tests
> SDKS-690-Input validation Refactor and new tests added

- src/main/java/io/split/android/client/LocalhostSplitFactory.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/cache/SplitCache.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/main/java/io/split/android/client/storage/MemoryAndFileStorage.java
- src/test/java/io/split/android/client/FileStorageTest.java
- src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Fixed issue about returning CONTROL in plain mode
- Added tests for SplitCache FileStorage components
> SDKS-697: Fixed issue when plain mode. 

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/LocalhostSplitFactory.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/cache/SplitCache.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/main/java/io/split/android/client/storage/MemoryAndFileStorage.java
- src/test/java/io/split/android/client/FileStorageTest.java
- src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Fixed issue when airplane mode
> Release 2.2.1

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/AlwaysReturnControlSplitClient.java
- src/main/java/io/split/android/client/LocalhostSplitClient.java
- src/main/java/io/split/android/client/SplitClient.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/TrackClientImpl.java
- src/main/java/io/split/android/client/dtos/Event.java
- src/main/java/io/split/android/client/track/TrackClientConfig.java
- src/main/java/io/split/android/client/validators/ValidationConfig.java
- src/test/java/io/split/android/client/events/TrackClientImplTest.java
- src/test/java/io/split/android/fake/ExecutorServiceMock.java
- Added properties field to track event
- Added properties validations
> Track properties

- src/main/java/io/split/android/client/TrackClientImpl.java
- src/main/java/io/split/android/client/utils/Json.java
- Updated Gson builder config to avoid removing null value properties
> Changed Gson config to not remove null values

- build.gradle
- src/main/java/io/split/android/client/TrackClientImpl.java
- src/main/java/io/split/android/client/track/TrackClientConfig.java
- Fixing centinel issue on tracks
- Removed hardcoded line for testing
> Removed hardcoded line for test

- src/main/java/io/split/android/client/SplitFactoryImpl.java
> Merge track properties from master to development

- src/main/java/io/split/android/client/TrackClientImpl.java
- src/main/java/io/split/android/client/validators/ValidationMessageLoggerImpl.java
- src/test/java/io/split/android/client/events/TrackClientImplTest.java
- Solved some track properties merge issues
> Fixed some merge issues

- src/main/java/io/split/android/client/EvaluatorImpl.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/TreatmentLabels.java
- src/main/java/io/split/android/client/validators/SplitValidator.java
- src/main/java/io/split/android/client/validators/SplitValidatorImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManager.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/main/java/io/split/android/client/validators/ValidationMessageLogger.java
- src/main/java/io/split/android/client/validators/ValidationMessageLoggerImpl.java
- src/test/java/io/split/android/client/SplitClientImplTest.java
- src/test/java/io/split/android/client/TreatmentManagerTest.java
- src/test/java/io/split/android/client/utils/SplitClientImplFactory.java
- src/test/java/io/split/android/client/validators/SplitValidatorTest.java
- src/test/java/io/split/android/fake/SplitCacheStub.java
- Added validation to treatment manager
- Added new NOT READY label and corresponding validations
- Added UT
- Updated get treatment tests to wait for SDK Ready event.
> SDKS-527: Input validation. Split validation and Not Ready label

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/HttpMySegmentsFetcher.java
- src/main/java/io/split/android/client/HttpSplitChangeFetcher.java
- Added missing support to some Json parsing requests
> SDKS-782: UTF 8 support hotfix

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/cache/SplitCache.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Synchronizing functions
- Adding defensive code to validate null values
> Fixing concurrency issue when writting splits to disk

- src/main/java/io/split/android/client/HttpSplitChangeFetcher.java
- src/main/java/io/split/android/engine/experiments/RefreshableSplitFetcher.java
- src/main/java/io/split/android/engine/experiments/SplitChangeFetcher.java
- src/main/java/io/split/android/engine/experiments/SplitFetcher.java
- src/test/java/io/split/android/engine/experiments/AChangePerCallSplitChangeFetcher.java
- Loading from cache out of main thread
> SDKS: 799: Issue when firing sdk ready event when no network available

- src/main/java/io/split/android/client/cache/SplitCache.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Using concurrent classes
- Improved Split cache tests
> SDKS-791: Fixing issue when writing splits on disk in app BG

- src/main/java/io/split/android/client/dtos/ChunkHeader.java
- src/main/java/io/split/android/client/dtos/Event.java
- src/main/java/io/split/android/client/impressions/ImpressionsStorageManager.java
- src/main/java/io/split/android/client/impressions/StoredImpressions.java
- src/main/java/io/split/android/client/storage/FileStorage.java
- src/main/java/io/split/android/client/storage/IStorage.java
- src/main/java/io/split/android/client/storage/MemoryAndFileStorage.java
- src/main/java/io/split/android/client/storage/MemoryStorage.java
- src/main/java/io/split/android/client/track/EventsChunk.java
- src/main/java/io/split/android/client/track/TrackStorageManager.java
- src/test/java/io/split/android/engine/impressions/ImpressionsStorageTest.java
- src/test/java/io/split/android/engine/track/TrackStorageTest.java
- src/test/java/io/split/android/helpers/ResourcesFileStorage.java
- Store track events disk cache in chunks. Added tests for the feature
- Store impressions disk cache in chunks. Added tests for the feature
> SDKS-875: Store impressions and track disk cache in chunks

- src/androidTest/java/InitialChangeNumberTest.java
- src/androidTest/java/IntegrationTest.java
- src/main/AndroidManifest.xml
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/cache/SplitCache.java
- src/main/java/io/split/android/engine/experiments/RefreshableSplitFetcherProvider.java
- src/test/java/io/split/android/engine/splits/SplitCacheTest.java
- Using change number to make first request to server on init
- Updating tests to test this feature
> SDKS-986: Avoid -1 when fetching changes from server on sdk init

- src/test/java/io/split/android/client/events/TrackClientImplTest.java
- src/test/java/io/split/android/fake/ExecutorServiceMock.java
> Fixed track client test

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/impressions/ImpressionsFileStorage.java
- src/main/java/io/split/android/client/track/TracksFileStorage.java
- src/test/java/io/split/android/engine/impressions/ImpressionsStorageTest.java
- src/test/java/io/split/android/engine/track/TrackStorageTest.java
- Added defensive code
- Added test cases to validate the fix
> SDKS-1021: Fixed issue when loading empty file

- .github/pull_request_template.md
- CHANGES.txt
- CONTRIBUTORS-GUIDE.md
- Detailed-README.md
- README.md
https://splitio.atlassian.net/browse/SDKS-910
> Docs revamp

- build.gradle
- src/androidTest/assets/split_dependency.json
- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/integration/MultiFactoryTreatmentOnBGSaveTest.java
- Added test evaluating multifactory while calling onPause and onResume app events
> SDKS-1170: Added test to prevent multifactory issues

- src/main/java/io/split/android/client/LocalhostSplitFile.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/events/executors/SplitEventExecutorResources.java
- src/main/java/io/split/android/client/events/executors/SplitEventExecutorWithClient.java
- src/main/java/io/split/android/client/metrics/HttpMetrics.java
- src/main/java/io/split/android/client/network/URIBuilder.java
- src/main/java/io/split/android/client/service/SplitApiFacade.java
- src/main/java/io/split/android/client/service/SyncManagerImpl.java
- src/main/java/io/split/android/client/service/executor/SplitTaskExecutorImpl.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsSyncTask.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/main/java/io/split/android/client/storage/SplitStorageContainer.java
- src/main/java/io/split/android/client/storage/mysegments/MySegmentsStorageImpl.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitsStorageImpl.java
- src/main/java/io/split/android/client/storage/splits/SqLitePersistentSplitsStorage.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- Refactored CheckNotNull usage
> CheckNotNull refactor

- src/androidTest/java/storage/PersistentImpressionStorageTest.java
- src/main/java/io/split/android/client/dtos/KeyImpression.java
- src/main/java/io/split/android/client/service/events/EventsRecorderTask.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsRecorderTask.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsRecorderTaskConfig.java
- src/main/java/io/split/android/client/storage/impressions/PersistentImpressionsStorage.java
- src/main/java/io/split/android/client/storage/impressions/SqLitePersistentImpressionsStorage.java
- src/test/java/io/split/android/client/service/ImpressionsRecorderTaskTest.java
- Added impressions recording task and test
> SDKS-1041: Cache revamp. Impressions recording task

- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/androidTest/java/integration/InitialChangeNumberTest.java
- src/androidTest/java/integration/IntegrationTest.java
- src/androidTest/java/integration/MySegmentUpdatedTest.java
- src/androidTest/java/integration/MySegmentsServerErrorTest.java
- src/androidTest/java/integration/TrackTest.java
- src/androidTest/java/storage/MySegmentsStorageTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
> SKDS-1386:  SDK ready flag

- src/androidTest/java/helper/SplitEventTaskHelper.java
- src/androidTest/java/integration/InitialChangeNumberTest.java
- src/androidTest/java/integration/IntegrationTest.java
- src/androidTest/java/integration/MySegmentsServerErrorTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/events/executors/SplitEventExecutorFactory.java
- src/main/java/io/split/android/client/service/ServiceConstants.java
- src/main/java/io/split/android/client/service/splits/LoadSplitsTask.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- Fixing issue when sdk ready from cache event triggering before handler is added
- Adding and improving integration tests
> SDK-1386: SDK ready from cache fix

- src/main/AndroidManifest.xml
> SKDS-1420:  Manfiest cleanup

- src/androidTest/java/integration/IntegrationTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/network/HttpRequestImpl.java
- Fixing property validation issue for lists type and adding a new integration test
- Improving http client wrapper
> SDKS-1281: Track property list validation issue

- src/androidTest/java/integration/IntegrationTest.java
- src/main/java/io/split/android/client/api/Key.java
- Added constructor without bucketing key to Key component
- Integration test updated to use that constructor
- Deprecating some static methods to create key instance
> SDK-1424: Added convenience key constructor

- src/androidTest/java/integration/IntegrationTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- Fixed issue while evaluation cause for input validation
- Added new SDK_READY_FROM_CACHE evaluation test
- Adding missing input validation message
> Fixing Read_From_Cache event issue on Get Treatment

- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/SyncManagerFeedbackChannel.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/SyncManagerFeedbackChannelImpl.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/SyncManagerFeedbackListener.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/SyncManagerFeedbackMessage.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/SyncManagerFeedbackMessageType.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerChannelMessageTest.java
- src/test/java/io/split/android/http/SseClientTest.java
Channel to broadcast push notification news to other components
UT added
> SDKS-1464: Feedback loop

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/SseJwtParser.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/PushStatusEvent.java
- src/main/java/io/split/android/client/service/sseclient/notifications/ControlNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/IncomingNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/IncomingNotificationType.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java
- src/main/java/io/split/android/client/service/sseclient/notifications/RawNotification.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/test/java/io/split/android/client/service/sseclient/NotificationParserTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerChannelMessageTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- Added Push notifications Occupancy logic
- Added control notification parser
- UTs
> SDKS-1465: Push manager keeper - Occupancy logic

- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/notifications/ControlNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/IncomingNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationType.java
- src/main/java/io/split/android/client/service/sseclient/notifications/OccupancyNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/RawNotification.java
- src/test/java/io/split/android/client/service/sseclient/NotificationParserTest.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- Added logic to handle streaming disabled, enabled, paused and initial error
- Added UT for push notification manager checking this logic
> SDKS-1465: Push notification control messages

- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/PushStatusEvent.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- Running full sync after streaming connection is done.
- Test for the feature
> Sync after sse connection

- src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsSyncTask.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/main/java/io/split/android/client/service/splits/SplitsUpdateTask.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/main/java/io/split/android/client/service/workmanager/MySegmentsSyncWorker.java
- src/main/java/io/split/android/client/service/workmanager/SplitsSyncWorker.java
- src/test/java/io/split/android/client/service/MySegmentsSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitUpdateTaskTest.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/sseclient/SynchronizerTest.java
- Added retry while getting http error in sync tasks
- Updated and added unit tests
> Retry while running sync tasks

- src/androidTest/assets/push_msg-control.txt
- src/androidTest/assets/push_msg-occupancy.txt
- src/androidTest/java/fake/HttpStreamResponseMock.java
- src/androidTest/java/integration/streaming/ControlTest.java
- src/androidTest/java/integration/streaming/OccupancyTest.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- Added E2E tests for different occupancy messages (primary channel updates and secondary)
- Added E2E tests for control messages (stream pause, enable and disable)
- Added some debug logs.
> SDKS-1472: Push notification occupancy and control E2E tests

- src/main/java/io/split/android/client/service/executor/SplitTaskExecutionInfo.java
- src/main/java/io/split/android/client/service/http/HttpFetcherImpl.java
Removed commented and empty lines
> Push notification small adjustments

- src/main/java/io/split/android/client/ServiceEndpoints.java
Pointing to streaming auth service in prod
> Updating streaming auth url to prod

- build.gradle
- src/main/java/io/split/android/client/ServiceEndpoints.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- src/main/java/io/split/android/client/network/HttpRequestImpl.java
- src/main/java/io/split/android/client/network/HttpStreamRequestImpl.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/http/HttpClientTest.java
- Replaced HttpUrlConnection to allow implementing NTLM proxy authentication.
> SDKS-1726: Replaced HttpUrlConnection by OkHttp

- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/network/DevelopmentSSLFactory.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- Created a SSL factory to bypass some security checks at development time
- Added new config to enable this development mode
> SDKS-1727: Adding a dummy SSL factory for developing time purposes

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/network/HttpStreamRequestImpl.java
- src/main/java/io/split/android/client/service/sseclient/SseClient.java
> Fix for SSE connection not closing in some situation

- build.gradle
- split-proguard-rules.pro
- src/androidTest/java/tests/database/TrackDaoTest.java
- src/androidTest/java/tests/integration/InitialChangeNumberTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManager.java
- src/main/java/io/split/android/client/network/HttpStreamRequestImpl.java
- src/main/java/io/split/android/client/service/executor/SplitTaskExecutorImpl.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/SseClient.java
- src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorker.java
- src/main/java/io/split/android/client/service/sseclient/reactor/SplitUpdatesWorker.java
- src/main/java/io/split/android/client/service/sseclient/reactor/UpdateWorker.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/test/java/io/split/android/client/service/sseclient/SseClientTest.java
- Improved splits and my segment IOExecption handling
- Using weak references in sse client to avoid changes to have memory leaks
- Some SSE client test improved
> Fixed memory issue when recreating factories

- src/androidTest/assets/push_msg-segment_update_empty_payload.txt
- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/androidTest/java/tests/integration/streaming/MySegmentsSyncProcessTest.java
- src/main/java/io/split/android/client/service/executor/SplitTaskExecutorImpl.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java
- src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java
- Allowing to process null list on incoming my segments update event
- Adding unit and integration tests for the issue
> Fixing Sse empty segment list event process issue

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/service/events/EventsRecorderTask.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsRecorderTask.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/SseClient.java
- src/main/java/io/split/android/client/service/sseclient/SseConnectionManager.java
- src/main/java/io/split/android/client/service/sseclient/SseConnectionManagerImpl.java
- src/main/java/io/split/android/client/service/sseclient/SseConnectionManagerListener.java
- src/test/java/io/split/android/client/service/EventsRecorderTaskTest.java
- src/test/java/io/split/android/client/service/ImpressionsRecorderTaskTest.java
- src/test/java/io/split/android/client/service/SplitTaskExecutorTest.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/SseConnectionManagerTest.java
- Splitting push manager component. Extracting Sse connection handling logic to a new component.
- Test updated
> Splitting push manager

- CHANGES.txt
- build.gradle
> Release 2.6.4

- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/SyncConfig.java
- src/test/java/io/split/android/client/SyncConfigTest.java
- Added SplitFilters to split client config
- Added unit tests
> SDKS-1832: Split Filter config

- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/FilterGrouper.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/SyncConfig.java
- src/main/java/io/split/android/client/network/URIBuilder.java
- src/main/java/io/split/android/client/utils/StringHelper.java
- src/test/java/io/split/android/client/FilterBuilderTest.java
- src/test/java/io/split/android/client/FilterGrouperTest.java
- src/test/java/io/split/android/client/SyncConfigTest.java
- src/test/java/io/split/android/http/URIBuilderTest.java
- Added query string builder and tests
> SDKS-1833: Query string builder (Fetch especific split)

- .travis.yml
- CHANGES.txt
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManager.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- Preventing issues related to threading on lifecycle observer
> Lifecycle observe and destroy in main thread

- src/main/java/io/split/android/client/network/BaseHttpResponse.java
- src/main/java/io/split/android/client/network/BaseHttpResponseImpl.java
- src/main/java/io/split/android/client/service/http/HttpSseAuthTokenFetcher.java
- src/main/java/io/split/android/client/service/sseauthentication/SseAuthenticationResponseParser.java
- src/main/java/io/split/android/client/service/sseauthentication/SseAuthenticationTask.java
- src/main/java/io/split/android/client/service/sseclient/EventStreamParser.java
- src/main/java/io/split/android/client/service/sseclient/SseAuthenticationResponse.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/PushStatusEvent.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/sseclient/notifications/OccupancyNotification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/StreamingError.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NotificationManagerKeeper.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseAuthenticationResult.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseAuthenticator.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseHandler.java
- src/test/java/io/split/android/client/service/SseAuthenticationTaskTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationManagerKeeperTest.java
- src/test/java/io/split/android/client/service/sseclient/SseAuthenticatorTest.java
- src/test/java/io/split/android/client/service/sseclient/SseHandlerTest.java
- Added SSE handler, Notification manager keeper and see authenticator 
- Added tests for all new components. 
- Some support classes updated to be adapted to new sse error handling logic
> SDKS-2023: Manager keeper and SSE handler

- build.gradle
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManager.java
- src/main/java/io/split/android/client/service/ServiceFactory.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsSyncTask.java
- src/main/java/io/split/android/client/service/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/BackoffCounterTimer.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NewPushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NewSseClient.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NewSseClientImpl.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseDisconnectionTimer.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseHandler.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseRefreshTokenTimer.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/test/java/io/split/android/client/service/sseclient/EventStreamParserTest.java
- src/test/java/io/split/android/client/service/sseclient/NewPushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/NewSseClientTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationManagerKeeperTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/SseClientTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerChannelMessageTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- src/test/java/io/split/android/fake/NewSseClientMock.java
- SSE client and Push notification manager new implementation to handle connection atomically
- Added timer components to handle token refresh and backoff algorithm separately
- Added tests for new components and updated to check some existing features
> SDKS-2023: Streaming atomic connection

- src/main/java/io/split/android/client/service/sseclient/EventStreamParser.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseHandler.java
- src/test/java/io/split/android/client/service/sseclient/SseClientTest.java
- Updated logic to report push subsystem up to sync manager. Now it's informed when the first no error event is received
- Updated tests
> SDKS-2043: Streaming connection confirmation

- src/main/java/io/split/android/client/SplitFactoryImpl.java
Added missing input validation
> Missing input validation found and fixed

- src/main/java/io/split/android/client/service/impressions/ImpressionsRecorderTask.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- Stop polling and recording completely besides pausing executor when app host goes to BG
> Optimization when app goes to BG

- build.gradle
- src/androidTest/java/helper/IntegrationHelper.java
- src/main/java/io/split/android/client/network/SdkTargetPath.java
- src/test/java/io/split/android/http/URIBuilderTest.java
- Encoding unsafe chars when build URL (my segments key in particular)
- Adding tests
> SDKS-2286:  Encode no safe url chars

- build.gradle
- src/androidTest/AndroidManifest.xml
Updated Snakeyaml library version to 1.28
> SDKS-2447: Snakeyaml library update to 1.28

- src/androidTest/java/fake/HttpClientMock.java
- src/androidTest/java/fake/HttpClientStub.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/network/HttpClient.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- src/main/java/io/split/android/client/network/SplitHttpHeadersBuilder.java
- src/main/java/io/split/android/client/service/ServiceConstants.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/main/java/io/split/android/client/service/workmanager/SplitWorker.java
- src/test/java/io/split/android/client/service/MySegmentsSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java
- src/test/java/io/split/android/http/SplitHttpHeadersBuilderTest.java
- Fixing headers and updating tests.
> SDKS-2663: Telemetry ably metadata

- src/main/java/io/split/android/client/dtos/KeyImpression.java
- src/main/java/io/split/android/client/impressions/Impression.java
- src/main/java/io/split/android/client/service/impressions/ImpressionHasher.java
- src/main/java/io/split/android/client/service/impressions/ImpressionObserver.java
- src/test/java/io/split/android/client/service/ImpressionHasherTest.java
- src/test/java/io/split/android/client/service/ImpressionObserverTest.java
- Added impression observer and hasher
- Added tests for new component
> SDKS-2612: Impressions deduplication. Observer and hasher

- src/main/java/io/split/android/client/utils/MurmurHash3.java
- src/test/java/io/split/android/engine/splitter/HashConsistencyTest.java
Added murmur 64, 128 algorithm and tests (Same than used in Java)
> Added Murmur3 64_128 and tests

- src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentChangeV2Notification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationType.java
Added MY_SEGMENT_UPDATE_V2 notification dto
> SDKS-2969: Streaming V2. My segments DTOs

- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseHandler.java
- src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java
- src/test/java/io/split/android/client/service/sseclient/SseHandlerTest.java
- Added handler, processor and tests for MySegmentsUpdatedV2 - Unbounded notification
> SDKS-2974: My segments update v2 unbounded fetch request

- src/androidTest/assets/push_msg-segment_updV2.txt
- src/androidTest/java/fake/SynchronizerSpyImpl.java
- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/tests/integration/streaming/MySegmentsChangeV2Test.java
- src/androidTest/java/tests/service/MySegmentV2PayloadDecoderTest.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/common/CompressionType.java
- src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentChangeV2Notification.java
- src/main/java/io/split/android/client/service/sseclient/notifications/MySegmentUpdateStrategy.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationParser.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java
- src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorker.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerSpy.java
- src/sharedTest/java/helper/TestingData.java
- src/sharedTest/java/helper/TestingHelper.java
- src/test/java/io/split/android/client/service/sseclient/MySegmentsUpdateWorkerTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationProcessorTest.java
- Fixed some issues parsing my segments v2 notifications types
- Added integration tests for my segments v2
> SDKS-2978: Integration tests for my segments v2

- src/androidTest/assets/push_msg-segment_update_payload_generic.txt
- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/main/java/io/split/android/client/service/sseclient/feedbackchannel/PushStatusEvent.java
- src/main/java/io/split/android/client/service/sseclient/notifications/ControlNotification.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NotificationManagerKeeper.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/sharedTest/java/helper/TestingHelper.java
- src/sharedTest/java/io/split/sharedtest/fake/HttpStreamResponseMock.java
- Stream reset and test added
- Improved control test using sdk update feature
> SDKS-2964: Stream reset

- CHANGES.txt
> Added missed on merge changelog entry

- src/main/java/io/split/android/client/service/ServiceConstants.java
- src/main/java/io/split/android/client/service/sseclient/SseAuthenticationResponse.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseAuthenticator.java
- Set default streaming connection delay to 60 seconds
> Set default sse connection delay to 60 seconds

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/storage/legacy/FileStorageHelper.java
@
- Removing api hashing when creating db name
- Renaming old database (hashed name) to new name
> SDKS-3096: Removing hashing to create db name:

- schemas/io.split.android.client.storage.db.SplitRoomDatabase/3.json
- src/androidTest/java/tests/database/GeneralInfoDaoTest.java
- src/androidTest/java/tests/database/GenericDaoTest.java
- src/androidTest/java/tests/database/ImpressionDaoTest.java
- src/androidTest/java/tests/database/MySegmentDaoTest.java
- src/androidTest/java/tests/database/SplitDaoTest.java
- src/androidTest/java/tests/database/TrackDaoTest.java
- src/androidTest/java/tests/database/attributes/AttributesDaoTest.java
- src/main/java/io/split/android/client/storage/attributes/PersistentAttributesStorage.java
- src/main/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorage.java
- src/main/java/io/split/android/client/storage/db/MySegmentDao.java
- src/main/java/io/split/android/client/storage/db/SplitRoomDatabase.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/storage/db/attributes/AttributesDao.java
- src/main/java/io/split/android/client/storage/db/attributes/AttributesEntity.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/test/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorageTest.java
- Added component to persist an attribute map per user key.
- Extracted a base class for DAO instrumented tests.
> [SDKS-5278] Create persistent storage for user attributes

- src/main/java/io/split/android/client/storage/attributes/AttributesStorage.java
- src/main/java/io/split/android/client/storage/attributes/AttributesStorageImpl.java
- src/test/java/io/split/android/client/storage/attributes/AttributesStorageImplTest.java
- Created `AttributesStorage` component to act as entry point for stored attributes, either in memory or in persistent storage.
- Added associated tests.
> [SDKS-5279] AttributesStorage

- src/test/java/io/split/android/client/SplitClientImplTest.java
- src/test/java/io/split/android/client/utils/SplitClientImplFactory.java
Add updated tests to feature branch
> Sdks 5295 merge with develop

- src/main/java/io/split/android/client/RetryBackoffCounterTimerFactory.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/sseclient/BackoffCounter.java
- src/main/java/io/split/android/client/service/sseclient/FixedIntervalBackoffCounter.java
- src/main/java/io/split/android/client/service/sseclient/ReconnectBackoffCounter.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/BackoffCounterTimer.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/RetryBackoffCounterTimer.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/main/java/io/split/android/client/telemetry/TelemetrySynchronizer.java
- src/main/java/io/split/android/client/telemetry/TelemetrySynchronizerImpl.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/sseclient/ReconnectBackoffCounterTest.java
- src/test/java/io/split/android/client/service/sseclient/sseclient/RetryBackoffCounterTimerTest.java
- Added retry logic in case sending config telemetry fails.
> Config recorder retry

- src/main/java/io/split/android/client/telemetry/model/EventTypeEnum.java
- src/main/java/io/split/android/client/telemetry/model/HttpErrors.java
- src/main/java/io/split/android/client/telemetry/model/HttpLatencies.java
- src/main/java/io/split/android/client/telemetry/model/LastSync.java
- src/main/java/io/split/android/client/telemetry/model/MethodExceptions.java
- src/main/java/io/split/android/client/telemetry/model/MethodLatencies.java
- src/main/java/io/split/android/client/telemetry/model/Stats.java
- src/main/java/io/split/android/client/telemetry/model/streaming/StreamingEvent.java
- Added Telemetry Stats model and annotations json field names.
> Models for stats telemetry

- LICENSE.txt
- build.gradle
- src/test/java/io/split/android/engine/splitter/HashConsistencyTest.java
- Updated Guava, Gson and Android Test Core versions.
> Dependencies update

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/SplitManagerImpl.java
- Added exception handling for client and manager methods.
- Added version changes.
- Changed version to 2.9.0-rc2
> Exception handling in public methods

- CHANGES.txt
- build.gradle
Update dev with latest changes from master.
> 2.9.0 to development

- src/main/java/io/split/android/client/service/executor/SplitTaskBatchItem.java
- src/main/java/io/split/android/client/service/executor/parallel/SplitDeferredTaskItem.java
- src/main/java/io/split/android/client/service/executor/parallel/SplitParallelTaskExecutor.java
- src/main/java/io/split/android/client/service/executor/parallel/SplitParallelTaskExecutorImpl.java
- src/test/java/io/split/android/client/service/executor/parallel/SplitParallelTaskExecutorImplTest.java
Created component to execute a group of short lived tasks in parallel.
> Parallel task executor

- src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsTaskFactory.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsTaskFactoryConfiguration.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsTaskFactoryProvider.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsTaskFactoryProviderImpl.java
Extract creation of tasks related to my segments to a separate class.
> MySegments task factory

- .github/workflows/update-license-year.yml
> adding gha for updating license year

- build.gradle
- src/main/java/io/split/android/client/dtos/Event.java
- src/main/java/io/split/android/client/dtos/SerializableEvent.java
- src/main/java/io/split/android/client/service/events/EventsRequestBodySerializer.java
- src/test/java/io/split/android/client/service/HttpRecorderTest.java
> Release 2.9.1-rc3

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/SplitApiFacade.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactory.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/http/mysegments/MySegmentsFetcherFactory.java
- src/main/java/io/split/android/client/service/http/mysegments/MySegmentsFetcherFactoryImpl.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
Created factory to provide `HttpFetcher` used to request mySegments for different user keys.
> Factory for MySegments HttpFetcher

- src/androidTest/java/tests/database/MySegmentDaoTest.java
- src/androidTest/java/tests/integration/streaming/MySegmentsChangeV2Test.java
- src/androidTest/java/tests/integration/streaming/MySegmentsSyncProcessTest.java
- src/androidTest/java/tests/storage/LoadMySegmentsTaskTest.java
- src/androidTest/java/tests/storage/MySegmentsStorageTest.java
- src/androidTest/java/tests/storage/PersistentMySegmentStorageTest.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/telemetry/TelemetryTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/workmanager/MySegmentsSyncWorker.java
- src/main/java/io/split/android/client/storage/SplitStorageContainer.java
- src/main/java/io/split/android/client/storage/db/MySegmentDao.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/storage/mysegments/MySegmentsStorageContainer.java
- src/main/java/io/split/android/client/storage/mysegments/MySegmentsStorageContainerImpl.java
- src/main/java/io/split/android/client/storage/mysegments/MySegmentsStorageImpl.java
- src/main/java/io/split/android/client/storage/mysegments/PersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/telemetry/storage/TelemetryStatsProviderImpl.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/storage/mysegments/MySegmentsStorageContainerImplTest.java
- src/test/java/io/split/android/client/telemetry/storage/TelemetryStatsProviderImplTest.java
- Added matching key as property in `MySegmentsStorageImpl`.
- Created `MySegmentsStorageContainer` to retrieve and keep track of `MySegmentsStorage` instances for each key.
> Update in MySegments storage for multiple keys

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizer.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerFactory.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerFactoryImpl.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerRegister.java
- src/main/java/io/split/android/client/storage/attributes/AttributesStorageContainer.java
- src/main/java/io/split/android/client/storage/attributes/AttributesStorageContainerImpl.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerImplTest.java
Added `AttributesSynchronizer` component, following the same pattern used with `MySegmentsSynchronizer`. Each Attributes Sync notifies its Event Manager about internal events.
> AttributesSynchronizer

- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/events/EventsManagerRegistry.java
- src/main/java/io/split/android/client/events/FactoryEventsManager.java
- src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorkerRegistry.java
- src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorkerRegistryImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/attributes/AttributesSynchronizerRegistry.java
- src/main/java/io/split/android/client/service/synchronizer/mysegments/MySegmentsSynchronizerRegistry.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorkerRegistryImplTest.java
Renaming 'Register' classes and code cleanup.
> Registers improvement

- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/network/URIBuilder.java
- src/test/java/io/split/android/http/URIBuilderTest.java
Modified `URIBuilder` to be able to build urls with multiple query params having the same name.
> Multiple query parameters

- src/main/java/io/split/android/client/SplitClientFactory.java
- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/sseclient/notifications/NotificationProcessor.java
- src/main/java/io/split/android/client/service/sseclient/notifications/mysegments/MySegmentsNotificationProcessorRegistry.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegister.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- src/test/java/io/split/android/client/shared/ClientComponentsRegisterImplTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
- Created component which registers each new client's dependencies to allow synchronization.
- Streaming is restarted when a client is created.
> Register client's dependencies

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/mysegments/MySegmentsBulkSyncTask.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- src/main/java/io/split/android/client/service/workmanager/MySegmentsSyncWorker.java
- src/test/java/io/split/android/client/service/mysegments/MySegmentsBulkSyncTaskTest.java
Updated `MySegmentsSyncWorker` to be able to launch synchronization task for every key.
> MySegments background sync for multiple keys

- src/main/java/io/split/android/client/service/sseclient/sseclient/PushNotificationManagerDeferredStartTask.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/test/java/io/split/android/client/service/sseclient/sseclient/PushNotificationManagerDeferredStartTaskTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
- Added task to launch a task for connection to streaming, in order to avoid unnecessary calls when instantiating multiple clients.
> Task to perform delayed streaming connection

- src/main/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorkerRegistryImpl.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/reactor/MySegmentsUpdateWorkerRegistryImplTest.java
- Start MySegmentsUpdateWorker after registering it, if necessary.
> Dynamically start my segments updater

- .github/workflows/update-license-year.yml
- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/dtos/Event.java
- src/main/java/io/split/android/client/dtos/SerializableEvent.java
- src/main/java/io/split/android/client/service/events/EventsRequestBodySerializer.java
- src/test/java/io/split/android/client/service/HttpRecorderTest.java
- src/test/java/io/split/android/client/service/events/EventsRequestBodySerializerTest.java
Updating multi-client baseline with development
> Update multiclient baseline

- build.gradle
> Version 2.10.0-rc2

- CHANGES.txt
- build.gradle
> Release 2.10.0

- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/tests/service/EventsRequestTest.java
- src/androidTest/java/tests/service/ImpressionsRequestTest.java
- src/main/java/io/split/android/client/service/events/EventsRecorderTask.java
Added integration tests for events and impressions request bodies.
> Integration tests for events & impressions request bodies

- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- src/main/java/io/split/android/client/service/workmanager/MySegmentsSyncWorker.java
- src/test/java/io/split/android/client/service/synchronizer/WorkManagerWrapperTest.java
> Tests for WM wrapper

- build.gradle
> Version 2.10.1-rc1

- CHANGES.txt
- build.gradle
> Release 2.10.1

- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/main/java/io/split/android/client/service/executor/SplitTaskExecutionInfo.java
- src/main/java/io/split/android/client/service/sseclient/notifications/ControlNotification.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NotificationManagerKeeper.java
- src/test/java/io/split/android/client/service/sseclient/NotificationManagerKeeperTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationParserTest.java
Handle `STREAMING_RESUMED` push event.
> Add resumed streaming state

- src/main/java/io/split/android/client/service/impressions/unique/MTK.java
- src/main/java/io/split/android/client/service/impressions/unique/UniqueKey.java
- src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysTracker.java
- src/main/java/io/split/android/client/storage/StoragePusher.java
- src/main/java/io/split/android/client/storage/impressions/PersistentImpressionsCountStorage.java
- src/main/java/io/split/android/client/storage/impressions/PersistentImpressionsStorage.java
- src/main/java/io/split/android/client/storage/impressions/PersistentImpressionsUniqueStorage.java
- src/main/java/io/split/android/client/storage/impressions/PersistentStorage.java
- DTOs and basic interfaces for MTKs.
> DTOs for MTKs

- src/androidTest/assets/bucket_split_test.json
- src/androidTest/java/tests/integration/shared/SharedClientsIntegrationTest.java
- src/androidTest/java/tests/integration/telemetry/TelemetryIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/api/Key.java
- src/main/java/io/split/android/client/events/EventsManagerCoordinator.java
- src/main/java/io/split/android/client/events/EventsManagerRegistry.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- src/main/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImpl.java
- src/main/java/io/split/android/client/shared/BaseSplitClientContainer.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegister.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainer.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/main/java/io/split/android/client/storage/splits/PersistentSplitsStorage.java
- src/test/java/io/split/android/client/events/EventsManagerCoordinatorTest.java
- src/test/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImplTest.java
- src/test/java/io/split/android/client/shared/ClientComponentsRegisterImplTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
- Differentiate client instances by `Key`
> Differentiate SplitClient by Key

- schemas/io.split.android.client.storage.db.SplitRoomDatabase/4.json
- src/androidTest/java/io/split/android/client/storage/db/impressions/unique/UniqueKeysDaoTest.java
- src/main/java/io/split/android/client/service/impressions/unique/UniqueKey.java
- src/main/java/io/split/android/client/storage/SqLitePersistentStorage.java
- src/main/java/io/split/android/client/storage/db/SplitRoomDatabase.java
- src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeyEntity.java
- src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeysDao.java
- src/main/java/io/split/android/client/storage/impressions/SqlitePersistentUniqueStorage.java
- src/test/java/io/split/android/client/storage/impressions/SqlitePersistentUniqueStorageTest.java
- Added Persistent Storage for UniqueKeys, in line with the pattern used for Impressions & Events.
> Unique Keys persistent storage

- build.gradle
> Version 2.10.2-rc1

- src/main/java/io/split/android/client/localhost/LocalhostYamlFileParser.java
> Fix error message

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/network/SdkTargetPath.java
- src/main/java/io/split/android/client/service/ServiceFactory.java
- src/main/java/io/split/android/client/service/SplitApiFacade.java
- src/main/java/io/split/android/client/service/impressions/unique/MTKRequestBodySerializer.java
- src/test/java/io/split/android/client/network/SdkTargetPathTest.java
- src/test/java/io/split/android/client/service/impressions/unique/MTKRequestBodySerializerTest.java
- Added HttpRecorder & Serializer for unique keys.
> HttpRecorder for MTKs

- CHANGES.txt
- build.gradle
- src/androidTest/assets/bucket_split_test.json
- src/androidTest/java/tests/integration/shared/SharedClientsIntegrationTest.java
- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/androidTest/java/tests/integration/telemetry/TelemetryIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/api/Key.java
- src/main/java/io/split/android/client/events/EventsManagerCoordinator.java
- src/main/java/io/split/android/client/events/EventsManagerRegistry.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- src/main/java/io/split/android/client/localhost/LocalhostYamlFileParser.java
- src/main/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImpl.java
- src/main/java/io/split/android/client/service/executor/SplitTaskExecutionInfo.java
- src/main/java/io/split/android/client/service/sseclient/notifications/ControlNotification.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NotificationManagerKeeper.java
- src/main/java/io/split/android/client/shared/BaseSplitClientContainer.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegister.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainer.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/main/java/io/split/android/client/storage/splits/PersistentSplitsStorage.java
- src/test/java/io/split/android/client/events/EventsManagerCoordinatorTest.java
- src/test/java/io/split/android/client/localhost/LocalhostYamlParserTest.java
- src/test/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImplTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationManagerKeeperTest.java
- src/test/java/io/split/android/client/service/sseclient/NotificationParserTest.java
- src/test/java/io/split/android/client/shared/ClientComponentsRegisterImplTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
- src/test/resources/splits_incorrect_value.yaml
> Release 2.10.2

- src/androidTest/java/tests/workmanager/WMWorkersSetupTest.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/service/ServiceConstants.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- src/main/java/io/split/android/client/service/workmanager/EventsRecorderWorker.java
- src/main/java/io/split/android/client/service/workmanager/ImpressionsRecorderWorker.java
- src/main/java/io/split/android/client/service/workmanager/UniqueKeysRecorderWorker.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
Added worker for unique keys recording.
> Background job for unique keys

- src/androidTest/java/tests/service/UniqueKeysIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerConfig.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsMode.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java
Added internal impression mode.
> Internal impression mode

- schemas/io.split.android.client.storage.db.SplitRoomDatabase/4.json
- src/androidTest/java/io/split/android/client/storage/db/impressions/unique/UniqueKeysDaoTest.java
- src/androidTest/java/tests/service/UniqueKeysIntegrationTest.java
- src/main/java/io/split/android/client/service/impressions/unique/UniqueKeysRecorderTask.java
- src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeyEntity.java
- src/test/java/io/split/android/client/service/impressions/unique/UniqueKeysRecorderTaskTest.java
- Removed uniqueness in unique keys entity.
- Merge features when building request body.
> Multiple unique key entries per user key

- src/androidTest/java/helper/DatabaseHelper.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncBackgroundTask.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/test/java/io/split/android/client/service/SplitBackgroundSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitUpdateTaskTest.java
- src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java
Check if filter has changed in order to ignore storage change number.
> Account for filter in CDN bypass

- CHANGES.txt
- build.gradle
- src/androidTest/java/helper/DatabaseHelper.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncBackgroundTask.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncTask.java
- src/test/java/io/split/android/client/service/SplitBackgroundSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitSyncTaskTest.java
- src/test/java/io/split/android/client/service/SplitUpdateTaskTest.java
- src/test/java/io/split/android/client/service/SplitsSyncHelperTest.java
> Release 2.10.3

- src/androidTest/java/fake/LifecycleManagerStub.java
- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/tests/integration/LifecyleOnBGTest.java
- src/androidTest/java/tests/integration/SingleSyncTest.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManager.java
- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManagerImpl.java
- Added integration test and fixed some issues.
> SDKS-5907: Single sync tests

- CHANGES.txt
- build.gradle
- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/androidTest/java/tests/integration/SingleSyncTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
> SDKS-5909: Single sync config rename

- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/test/java/io/split/android/client/events/EventsManagerCoordinatorTest.java
- Add merged attributes when logging Impression.
> Log merged attributes in Impression Logger

- src/main/java/io/split/android/client/lifecycle/SplitLifecycleManagerImpl.java
- src/main/java/io/split/android/client/shared/ClientComponentsRegisterImpl.java
- src/test/java/io/split/android/client/shared/ClientComponentsRegisterImplTest.java
- Added null check for component in Lifecycle Manager.
- Added call to unregister events manager.
- Added additional test.
> Lifecycle Manager improvement

- CHANGES.txt
- build.gradle
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/telemetry/storage/InMemoryTelemetryStorage.java
- src/test/java/io/split/android/client/metrics/BinarySearchLatencyTrackerTest.java
- src/test/java/io/split/android/client/telemetry/storage/InMemoryTelemetryStorageTest.java
- Fixed telemetry latencies bucket.
> Telemetry latencies

- build.gradle
> 2.12.3-rc1

- src/androidTest/java/tests/integration/SingleSyncTest.java
- src/androidTest/java/tests/service/UniqueKeysIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerConfig.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsMode.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- Enabled `NONE` impressions mode.
> Enable NONE impressions mode

- build.gradle
- src/androidTest/java/tests/integration/MySegmentUpdatedTest.java
- src/androidTest/java/tests/integration/ProxyFactoryTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- src/main/java/io/split/android/client/network/HttpProxy.java
- src/main/java/io/split/android/client/network/SdkTargetPath.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/test/java/io/split/android/http/HttpClientTest.java
- Changed setup of Proxy to allow for initialization in main thread
- Updated OkHttp version to `3.12.13`
- Added new tests.
> Proxy improvements

- src/main/java/io/split/android/client/RetryBackoffCounterTimerFactory.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerRetryTimerProvider.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerRetryTimerProviderImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java
- src/test/java/io/split/android/client/service/impressions/ImpressionManagerRetryTimerProviderImplTest.kt
- src/test/java/io/split/android/client/service/sseclient/sseclient/RetryBackoffCounterTimerTest.java
- Replicated retry logic of unique keys in impressions, counts and events.
> Retries for impressions and events

- src/main/java/io/split/android/client/SplitClientConfig.java
- Added syncEnabled configuration.
> Add config parameter

- src/androidTest/java/helper/IntegrationHelper.java
- src/main/java/io/split/android/client/storage/impressions/ImpressionsStorage.java
- src/main/java/io/split/android/client/storage/impressions/Storage.java
- src/sharedTest/java/helper/TestingHelper.java
- src/test/java/io/split/android/client/storage/impressions/ImpressionsStorageTest.java
- Added impressions in memory storage and tests
> SDKS-6340: Added in memory impressions storage

- src/main/java/io/split/android/client/EventsTracker.java
- src/main/java/io/split/android/client/EventsTrackerImpl.java
- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManager.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java
- src/test/java/io/split/android/client/SplitClientImplBaseTest.java
- src/test/java/io/split/android/client/SplitClientImplTelemetryTest.java
- src/test/java/io/split/android/client/service/events/EventsTrackerTest.java
- src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java
- src/test/java/io/split/android/client/utils/SplitClientImplFactory.java
- Enable / disable tracking added
- Tests for feature
- Extracted events tracking logic to a new component
> SDKS-6299: Enable / disable tracking

- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/main/java/io/split/android/client/EventsTrackerImpl.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SynchronizerImpl.java
- src/main/java/io/split/android/client/shared/UserConsent.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/sseclient/SyncManagerTest.java
- Enable recording when GRANTED only
- Updated tests
- Added test
> SDKS-6300: User consent enable/disable recording

- build.gradle
> 2.13.2-rc1

- build.gradle
> 2.13.2-rc2

- src/androidTest/java/fake/SyncManagerStub.java
- src/main/java/io/split/android/client/EventsTracker.java
- src/main/java/io/split/android/client/EventsTrackerImpl.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactory.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/UserConsentManager.java
- src/main/java/io/split/android/client/UserConsentManagerImpl.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/impressions/ImpressionManagerImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManager.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/main/java/io/split/android/client/storage/common/SplitStorageContainer.java
- src/main/java/io/split/android/client/storage/db/EventDao.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/storage/events/EventsStorage.java
- src/main/java/io/split/android/client/storage/events/SqLitePersistentEventsStorage.java
- src/main/java/io/split/android/client/storage/impressions/ImpressionsStorage.java
- src/test/java/io/split/android/client/UserConsentManagerTest.java
- src/test/java/io/split/android/client/service/SynchronizerTest.java
- src/test/java/io/split/android/client/service/events/EventsTrackerTest.java
- src/test/java/io/split/android/client/service/impressions/ImpressionManagerImplTest.java
- src/test/java/io/split/android/client/service/telemetry/SynchronizerImplTelemetryTest.java
- src/test/java/io/split/android/client/shared/SplitClientContainerImplTest.java
-- Added user consent manager component
- Added init SDK based on user consent status code
- Added tests for new component
- Updated existing tests
> SDKS-6302: User consent method and init sdk code

- src/main/java/io/split/android/client/shared/UserConsent.java
- src/main/java/io/split/android/client/telemetry/model/Config.java
- src/main/java/io/split/android/client/telemetry/storage/TelemetryConfigProviderImpl.java
- src/test/java/io/split/android/client/UserConsentManagerTest.java
- src/test/java/io/split/android/client/metrics/BinarySearchLatencyTrackerTest.java
- src/test/java/io/split/android/client/telemetry/TelemetryConfigBodySerializerTest.java
- Added User Consent value to telemetry config
- Updated tests
> User Consent  telemetry

- src/main/java/io/split/android/client/SplitClientConfig.java
- Re added deprecated config parameters.
> Add timeout configs

- build.gradle
- src/androidTest/java/tests/integration/IntegrationTest.java
- src/androidTest/java/tests/integration/MySegmentUpdatedTest.java
- src/androidTest/java/tests/integration/MySegmentsServerErrorTest.java
- src/androidTest/java/tests/integration/ProxyFactoryTest.java
- src/androidTest/java/tests/integration/SingleSyncTest.java
- src/androidTest/java/tests/integration/SplitChangesTest.java
- src/androidTest/java/tests/integration/shared/SharedClientsIntegrationTest.java
- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/androidTest/java/tests/integration/streaming/MySegmentsSyncProcessTest.java
- src/androidTest/java/tests/integration/streaming/SseAuthFail5xxTest.java
- src/androidTest/java/tests/integration/streaming/SseConnectionFail5xxTest.java
- src/androidTest/java/tests/integration/streaming/StreamingDisabledTest.java
- src/androidTest/java/tests/integration/streaming/StreamingInitializationTest.java
- src/androidTest/java/tests/integration/userconsent/UserConsentModeOptimizedTest.kt
- src/androidTest/java/tests/storage/MySegmentsStorageTest.java
- Added Android test orchestrator to run instrumented tests.
- Improved various instrumented tests to reduce flakiness.
> Instrumented tests improvements

- src/androidTest/java/tests/storage/cipher/KeyManagerTest.java
- src/androidTest/java/tests/storage/cipher/provider/AndroidKeyStoreKeyProviderTest.java
- src/androidTest/java/tests/storage/cipher/provider/LegacyKeyProviderTest.java
- src/main/java/io/split/android/client/storage/cipher/KeyManager.java
- src/main/java/io/split/android/client/storage/cipher/provider/AndroidKeyStoreKeyProvider.java
- src/main/java/io/split/android/client/storage/cipher/provider/KeyProvider.java
- src/main/java/io/split/android/client/storage/cipher/provider/LegacyKeyProvider.java
- Created a key generator for using a Cipher.
> Key generator

- src/androidTest/java/tests/storage/LoadSplitTaskTest.java
- src/androidTest/java/tests/storage/PersistentSplitsStorageTest.java
- src/androidTest/java/tests/storage/SplitsStorageTest.java
- src/main/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformer.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/main/java/io/split/android/client/storage/splits/SqLitePersistentSplitsStorage.java
- src/test/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformerTest.java
- src/test/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformerTest.java
- Added `SplitCipher` in split transformers.
> Cipher in split transformers

- src/androidTest/java/tests/storage/LoadMySegmentsTaskTest.java
- src/androidTest/java/tests/storage/LoadSplitTaskTest.java
- src/androidTest/java/tests/storage/MySegmentsStorageTest.java
- src/androidTest/java/tests/storage/PersistentMySegmentStorageTest.java
- src/androidTest/java/tests/storage/PersistentSplitsStorageTest.java
- src/androidTest/java/tests/storage/SplitsStorageTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/synchronizer/WorkManagerWrapper.java
- src/main/java/io/split/android/client/service/workmanager/MySegmentsSyncWorker.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformer.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/main/java/io/split/android/client/storage/splits/SqLitePersistentSplitsStorage.java
- src/test/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorageTest.java
- src/test/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformerTest.java
- src/test/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformerTest.java
- Added `SplitCipher` in segments.
> Cipher in segments

- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorage.java
- src/main/java/io/split/android/client/storage/db/StorageFactory.java
- src/main/java/io/split/android/client/utils/Json.java
- src/test/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorageTest.java
- Added `SplitCipher` for attributes.
> Cipher in attributes

- src/main/java/io/split/android/client/storage/cipher/CBCCipher.java
- src/main/java/io/split/android/client/storage/cipher/CBCCipherProvider.java
- src/main/java/io/split/android/client/storage/cipher/CipherProvider.java
- src/main/java/io/split/android/client/storage/cipher/ObjectPool.java
- src/main/java/io/split/android/client/storage/cipher/ObjectPoolFactory.java
- src/test/java/io/split/android/client/storage/cipher/ObjectPoolTest.kt
- Added object pool for cipher instances.
> Cipher pool

- src/main/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorage.java
- src/main/java/io/split/android/client/storage/cipher/ApplyCipherTask.java
- src/main/java/io/split/android/client/storage/db/ImpressionDao.java
- src/main/java/io/split/android/client/storage/db/ImpressionEntity.java
- src/main/java/io/split/android/client/storage/db/MySegmentDao.java
- src/main/java/io/split/android/client/storage/db/SplitDao.java
- src/main/java/io/split/android/client/storage/db/attributes/AttributesDao.java
- src/main/java/io/split/android/client/storage/impressions/SqLitePersistentImpressionsStorage.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformer.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/test/java/io/split/android/client/storage/attributes/SqLitePersistentAttributesStorageTest.java
- src/test/java/io/split/android/client/storage/cipher/ObjectPoolTest.kt
- src/test/java/io/split/android/client/storage/impressions/SqlitePersistentImpressionsStorageTest.java
- src/test/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorageTest.java
- src/test/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformerTest.java
- Encrypting remaining fields.
> Encrypt remaining fields

- src/main/java/io/split/android/client/SplitManager.java
- src/main/java/io/split/android/client/api/SplitView.java
- Updated javadocs in SplitManager and SplitView.
> Javadoc update in SplitManager

- src/main/java/io/split/android/client/SplitClient.java
- Updated SplitClient javadoc.
> Javadoc update

- src/androidTest/java/fake/SplitClientStub.java
- src/main/java/io/split/android/client/AlwaysReturnControlSplitClient.java
- src/main/java/io/split/android/client/SplitClient.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryBuilder.java
- src/main/java/io/split/android/client/SplitManager.java
- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- Renamed public method parameters
> Rename public parameters

- CHANGES.txt
- build.gradle
> Version 3.2.1

- README.md
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/storage/cipher/EncryptionMigrationTask.java
- src/main/java/io/split/android/client/storage/cipher/SplitEncryptionLevel.java
- src/test/java/io/split/android/client/storage/cipher/EncryptionMigrationTaskTest.kt
- Pass already instantiated cipher to the encryption migration task.
> Refactor cipher creation

- build.gradle
> Version 3.2.2-rc1

- build.gradle
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/service/executor/TaskWrapper.java
- src/test/java/io/split/android/client/SplitFactoryHelperTest.kt
- Set migration listener as property in SplitFactory.
> Version 3.2.2-rc2

- CHANGES.txt
- build.gradle
- Updated version and changes.
> Version 3.2.2

- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/androidTest/java/tests/integration/streaming/SyncGuardianIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/service/splits/SplitsSyncHelper.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/PushNotificationManager.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseAuthenticator.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseDisconnectionTimer.java
- src/main/java/io/split/android/client/service/synchronizer/SyncGuardianImpl.java
- src/main/java/io/split/android/client/service/synchronizer/SyncManagerImpl.java
- src/test/java/io/split/android/client/service/sseclient/PushNotificationManagerTest.java
- src/test/java/io/split/android/client/service/sseclient/SseAuthenticatorTest.java
- src/test/java/io/split/android/client/service/sseclient/sseclient/SseDisconnectionTimerTest.java
- src/test/java/io/split/android/client/service/synchronizer/SyncGuardianImplTest.java
- Added integration tests for `SyncGuardian` flows.
> Integration tests for sync

- src/main/java/io/split/android/client/service/splits/SplitInPlaceUpdateTask.java
- src/main/java/io/split/android/client/service/sseclient/reactor/SplitUpdatesWorker.java
- src/test/java/io/split/android/client/service/sseclient/SplitUpdateWorkerTest.java
- src/test/java/io/split/android/fake/SplitTaskExecutorStub.java
- Added functionality to always fallback to fetching flags in case there is a failure in parsing the new notification data.
> Update worker improvements

- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/service/splits/FilterSplitsInCacheTask.java
- src/test/java/io/split/android/client/FilterBuilderTest.java
- Added logic to build the filters query parameter for sets.
> Sets in FilterBuilder

- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/FilterGrouper.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/splits/FilterSplitsInCacheTask.java
- src/test/java/io/split/android/client/FilterBuilderTest.java
- src/test/java/io/split/android/client/service/FilterSplitsInCacheTaskTest.java
- Modified the cache filter task to filter according to sets if that type of filter is present.
> Modify cache filtering task

- src/androidTest/java/tests/storage/SplitsStorageTest.java
- src/main/java/io/split/android/client/api/SplitView.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitsStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitsStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitsStorageImpl.java
- Added flags set cache to feature flags storage.
> Sets cache in memory storage

- src/androidTest/java/fake/SplitClientStub.java
- src/main/java/io/split/android/client/AlwaysReturnControlSplitClient.java
- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/SplitClient.java
- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/SplitClientImpl.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java
- src/main/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImpl.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerFactoryImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/test/java/io/split/android/client/TreatmentManagerTelemetryTest.java
- src/test/java/io/split/android/client/TreatmentManagerTest.java
- src/test/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImplTest.java
- src/test/java/io/split/android/client/utils/SplitClientImplFactory.java
- Added new evaluation methods to `SplitClient` interface.
- Added the configured sets to the treatment manager, which will be used for validations.
- Implementations for the new methods have been intentionally left undone; this PR is to reduce changes in the following one.
> New client methods groundwork

- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/SyncConfig.java
- Add missing log message for filter type conflict.
> Add filter types log message

- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/api/SplitView.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- src/main/java/io/split/android/client/validators/TreatmentManagerFactoryImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/test/java/io/split/android/client/SplitManagerImplTest.java
- src/test/java/io/split/android/client/TreatmentManagerTelemetryTest.java
- src/test/java/io/split/android/client/TreatmentManagerTest.java
- src/test/java/io/split/android/client/TreatmentManagerWithFlagSetsTest.java
- Added `defaultTreatment` in `SplitView`.
- Added feature flag name as part of the readiness warning log message.
> Default treatment in SplitView

- src/androidTest/java/tests/integration/streaming/ControlTest.java
- src/androidTest/java/tests/integration/telemetry/TelemetryIntegrationTest.java
- src/main/java/io/split/android/client/SplitFilter.java
- src/main/java/io/split/android/client/SplitManagerImpl.java
- src/main/java/io/split/android/client/SyncConfig.java
- src/main/java/io/split/android/client/api/SplitView.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitClient.java
- src/main/java/io/split/android/client/service/executor/SplitTaskFactoryImpl.java
- src/main/java/io/split/android/client/validators/FlagSetsValidatorImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerFactoryImpl.java
- src/main/java/io/split/android/client/validators/TreatmentManagerImpl.java
- src/test/java/io/split/android/client/SplitManagerImplTest.java
- src/test/java/io/split/android/client/TreatmentManagerTelemetryTest.java
- src/test/java/io/split/android/client/TreatmentManagerTest.java
- src/test/java/io/split/android/client/TreatmentManagerWithFlagSetsTest.java
- src/test/java/io/split/android/client/validators/FlagSetsValidatorImplTest.java
- Fix sets counters in telemetry
> Fix sets counters for telemetry

- src/androidTest/java/tests/database/DatabaseInitializationTest.java
- src/androidTest/java/tests/integration/sets/FlagSetsEvaluationTest.java
- src/androidTest/java/tests/integration/sets/FlagSetsMultipleFactoryTest.java
- src/main/java/io/split/android/client/FilterBuilder.java
- Added instrumented tests for verifying db name with & without prefix.
- Added instrumented test for verifying db contents when using prefix.
> DB initialization tests

- src/androidTest/java/tests/database/DatabaseInitializationTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/main/java/io/split/android/client/validators/PrefixValidator.java
- src/main/java/io/split/android/client/validators/PrefixValidatorImpl.java
- src/test/java/io/split/android/client/SplitClientConfigTest.java
- src/test/java/io/split/android/client/validators/PrefixValidatorImplTest.java
- Added prefix config parameter validations.
> Prefix validation

- .github/workflows/instrumented.yml
- CHANGES.txt
- build.gradle
- gradle.properties
- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/androidTest/java/tests/database/DatabaseInitializationTest.java
- src/androidTest/java/tests/integration/sets/FlagSetsEvaluationTest.java
- src/androidTest/java/tests/integration/sets/FlagSetsMultipleFactoryTest.java
- src/main/java/io/split/android/client/FilterBuilder.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/SplitFactoryHelper.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/main/java/io/split/android/client/validators/PrefixValidator.java
- src/main/java/io/split/android/client/validators/PrefixValidatorImpl.java
- src/test/java/io/split/android/client/SplitClientConfigTest.java
- src/test/java/io/split/android/client/SplitFactoryHelperTest.kt
- src/test/java/io/split/android/client/validators/PrefixValidatorImplTest.java
> Release 3.5.0

- build.gradle
- deps.txt
- Added Gradle task to be executed for every build, updating the `deps.txt` file. This will allow us to verify changes in dependencies don't introduce any undesired new deps.
> Dependencies file

- src/androidTest/java/helper/TestableSplitConfigBuilder.java
- src/androidTest/java/tests/integration/ProxyFactoryTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- Replaced type of the `proxyAuthenticator` with `SplitAuthenticator`.
- Added integration test.
> Authenticator class replacement

- src/main/java/io/split/android/client/network/HttpStreamRequestImpl.java
- Added changes to the `HttpStreamRequestImpl` class.
> HttpStreamRequestImpl

- build.gradle
- deps.txt
- src/androidTest/java/tests/integration/ProxyFactoryTest.java
- src/androidTest/java/tests/service/UrlSanitizerTest.java
- src/main/java/io/split/android/client/SplitFactoryImpl.java
- src/main/java/io/split/android/client/network/BaseHttpResponseImpl.java
- src/main/java/io/split/android/client/network/UrlSanitizer.java
- src/main/java/io/split/android/client/network/UrlSanitizerImpl.java
- src/main/java/io/split/android/client/service/http/HttpFetcherImpl.java
- src/main/java/io/split/android/client/service/sseclient/EventStreamParser.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/SseClientImpl.java
- src/test/java/io/split/android/http/HttpClientTest.java
- Added changes in remaining classes.
- Changed minSdk to 19.
- Removed okhttp.
> Remaining changes; minSdk 19

- src/main/java/io/split/android/client/events/BaseEventsManager.java
- src/main/java/io/split/android/client/service/executor/SplitClientEventTaskExecutor.java
- src/main/java/io/split/android/client/service/executor/SplitSingleThreadTaskExecutor.java
- src/main/java/io/split/android/client/service/executor/ThreadFactoryBuilder.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/PushNotificationManager.java
- src/test/java/io/split/android/client/service/executor/ThreadFactoryBuilderTest.java
- Added `ThreadFactoryBuilder` from Guava, with minimal modifications.
> ThreadFactoryBuilder replacement

- src/androidTest/java/tests/service/ImpressionsObserverTest.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsObserver.java
- Replace Cache from Guava with Android's `LruCache`.
> Cache replacement

- src/main/java/io/split/android/client/storage/cipher/KeyManager.java
- src/main/java/io/split/android/client/storage/cipher/SplitCipher.java
- src/main/java/io/split/android/client/storage/cipher/provider/KeyProvider.java
- src/main/java/io/split/android/client/storage/db/SplitRoomDatabase.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/main/java/io/split/android/engine/experiments/ParsedSplit.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/CombiningMatcher.java
- src/test/java/io/split/android/client/SplitClientImplLegacyTest.java
- src/test/java/io/split/android/client/SplitManagerImplTest.java
- src/test/java/io/split/android/engine/ConditionsTestUtil.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/AttributeMatcherTest.java
- src/test/java/io/split/android/engine/matchers/CombiningMatcherTest.java
- src/test/java/io/split/android/engine/matchers/NegatableMatcherTest.java
- src/test/java/io/split/android/engine/matchers/strings/WhitelistMatcherTest.java
- src/test/java/io/split/android/engine/splitter/HashingTest.java
- src/test/java/io/split/android/engine/splitter/SplitterTest.java
- Replaced some List methods.
- Replaced `javax.annotation.Nullable` usages with `androidx.annotation.Nullable`.
> Replace annotations & List operations

- src/main/java/io/split/android/client/service/events/EventsRecorderTask.java
- src/main/java/io/split/android/client/storage/common/SqLitePersistentStorage.java
- src/main/java/io/split/android/client/storage/splits/SplitEntityToSplitTransformer.java
- src/main/java/io/split/android/client/storage/splits/SplitToSplitEntityTransformer.java
- src/main/java/io/split/android/client/storage/splits/SqLitePersistentSplitsStorage.java
- src/main/java/io/split/android/client/utils/Utils.java
- Replaced `Lists.partition` with own implementation.
> Replace Lists.partition

- src/main/java/io/split/android/client/FlagSetsFilterImpl.java
- src/main/java/io/split/android/client/dtos/SerializableEvent.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitsStorage.java
- src/main/java/io/split/android/client/service/executor/SplitBaseTaskExecutor.java
- src/main/java/io/split/android/client/service/executor/ThreadFactoryBuilder.java
- src/main/java/io/split/android/client/service/sseclient/sseclient/NotificationManagerKeeper.java
- src/main/java/io/split/android/client/shared/BaseSplitClientContainer.java
- src/main/java/io/split/android/client/storage/mysegments/MySegmentsStorageImpl.java
- src/main/java/io/split/android/client/telemetry/storage/InMemoryTelemetryStorage.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/Transformers.java
- src/test/java/io/split/android/engine/matchers/AttributeMatcherTest.java
- src/test/java/io/split/android/engine/splitter/HashingTest.java
- Replaced methods from `Maps` and `Sets`.
> Replace Maps & Sets

- src/main/java/io/split/android/client/utils/Utils.java
- src/test/java/io/split/android/client/utils/PartitionTest.java
- Unit tests for partition util method.
> Partition tests

- build.gradle
- deps.txt
- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/tests/integration/streaming/SyncGuardianIntegrationTest.java
- src/main/java/io/split/android/client/SplitClientConfig.java
- src/main/java/io/split/android/client/network/HttpClientImpl.java
- src/main/java/io/split/android/client/network/HttpResponseImpl.java
- src/main/java/io/split/android/client/network/HttpStreamResponseImpl.java
- src/main/java/io/split/android/client/network/PercentEscaper.java
- src/main/java/io/split/android/client/network/SdkTargetPath.java
- src/main/java/io/split/android/client/network/URIBuilder.java
- src/main/java/io/split/android/client/network/UnicodeEscaper.java
- src/main/java/io/split/android/client/network/UrlEscapers.java
- src/main/java/io/split/android/client/service/executor/parallel/SplitParallelTaskExecutorFactoryImpl.java
- src/main/java/io/split/android/client/storage/legacy/FileStorageHelper.java
- src/main/java/io/split/android/client/storage/mysegments/SqLitePersistentMySegmentsStorage.java
- src/main/java/io/split/android/client/utils/MemoryUtilsImpl.java
- src/main/java/io/split/android/client/utils/Utils.java
- src/main/java/io/split/android/client/validators/ApiKeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/EventValidatorImpl.java
- src/main/java/io/split/android/client/validators/KeyValidatorImpl.java
- src/main/java/io/split/android/client/validators/SplitValidatorImpl.java
- src/test/java/io/split/android/client/TreatmentManagerTest.java
- src/test/java/io/split/android/client/events/EventPropertiesProcessorTest.java
- src/test/java/io/split/android/client/utils/RepeatTest.java
- src/test/java/io/split/android/client/validators/EventValidatorTest.java
- src/test/java/io/split/android/client/validators/KeyValidatorTest.java
- src/test/java/io/split/android/engine/splitter/SplitterTest.java
- Removed Guava; only present for test builds.
- Added URL escaper from Guava.
- Replaced some missed helper methods.
- Added ThreadFactory for Parallel Task executor.
- Replaced Strings.repeat method.
> Url escaping

- src/main/java/io/split/android/client/EventsTrackerImpl.java
- src/main/java/io/split/android/client/FlagSetsFilter.java
- src/main/java/io/split/android/client/SplitClientFactoryImpl.java
- src/main/java/io/split/android/client/SplitFactoryBuilder.java
- src/main/java/io/split/android/client/events/SplitEventsManager.java
- src/main/java/io/split/android/client/localhost/LocalhostSplitFactory.java
- src/main/java/io/split/android/client/localhost/LocalhostSynchronizer.java
- src/main/java/io/split/android/client/localhost/shared/LocalhostSplitClientContainerImpl.java
- src/main/java/io/split/android/client/service/CleanUpDatabaseTask.java
- src/main/java/io/split/android/client/service/impressions/ImpressionsTaskFactory.java
- src/main/java/io/split/android/client/service/splits/SplitChangeProcessor.java
- src/main/java/io/split/android/client/service/sseclient/EventStreamParser.java
- src/main/java/io/split/android/client/service/synchronizer/mysegments/MySegmentsSynchronizerRegistryImpl.java
- src/main/java/io/split/android/client/service/telemetry/TelemetryTaskFactoryImpl.java
- src/main/java/io/split/android/client/service/workmanager/SplitsSyncWorker.java
- src/main/java/io/split/android/client/shared/SplitClientContainerImpl.java
- src/main/java/io/split/android/client/storage/cipher/ApplyCipherTask.java
- src/main/java/io/split/android/client/storage/cipher/EncryptionMigrationTask.java
- src/main/java/io/split/android/client/storage/db/EventDao.java
- src/main/java/io/split/android/client/storage/db/ImpressionDao.java
- src/main/java/io/split/android/client/storage/db/impressions/unique/UniqueKeyEntity.java
- src/main/java/io/split/android/client/storage/events/EventsStorage.java
- src/main/java/io/split/android/client/utils/Json.java
- src/main/java/io/split/android/client/utils/Zlib.java
- src/main/java/io/split/android/client/validators/TreatmentManagerFactory.java
- src/main/java/io/split/android/engine/matchers/MySegmentsMatcher.java
> Remove unused imports

- src/main/java/io/split/android/client/EvaluationResult.java
- src/main/java/io/split/android/client/EvaluatorImpl.java
- src/main/java/io/split/android/client/storage/attributes/AttributesStorageImpl.java
- src/test/java/io/split/android/engine/experiments/EvaluatorTest.java
- When exceptions are caught inside Evaluator, return an evaluation with EXCEPTION label.
> EvaluationResult with Exception label

- src/androidTest/java/tests/service/ImpressionsObserverTest.java
- src/main/java/io/split/android/client/service/impressions/observer/ImpressionsObserver.java
- src/main/java/io/split/android/client/service/impressions/observer/ImpressionsObserverImpl.java
- src/main/java/io/split/android/client/service/impressions/strategy/ImpressionStrategyProvider.java
- src/main/java/io/split/android/client/service/impressions/strategy/OptimizedStrategy.java
- src/test/java/io/split/android/client/service/impressions/strategy/OptimizedStrategyTest.kt
- Extracted interface for `ImpressionsObserver`.
> ImpressionsObserver interface

- src/androidTest/java/tests/service/ImpressionsObserverTest.java
- src/main/java/io/split/android/client/service/impressions/observer/ImpressionsObserver.java
- src/main/java/io/split/android/client/service/impressions/observer/ImpressionsObserverImpl.java
- src/main/java/io/split/android/client/service/impressions/strategy/ImpressionStrategyProvider.java
- src/main/java/io/split/android/client/service/impressions/strategy/OptimizedStrategy.java
- src/test/java/io/split/android/client/service/impressions/strategy/OptimizedStrategyTest.kt
> ImpressionsObserver factory to baseline

- src/main/java/io/split/android/client/TreatmentLabels.java
- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/DefaultConditionsProvider.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/experiments/UnsupportedMatcherException.java
- src/test/java/io/split/android/client/TreatmentLabelsTest.java
- src/test/java/io/split/android/engine/experiments/DefaultConditionsProviderTest.java
- src/test/java/io/split/android/engine/experiments/UnsupportedMatcherSplitParserTest.java
- Default conditions for unsupported matcher to baseline.
> Default conditions for unsupported matcher

- src/androidTest/assets/splitchanges_unsupported_matcher.json
- src/androidTest/java/tests/integration/matcher/UnsupportedMatcherTest.java
- Added instrumented tests for unsupported matcher.
> Unsupported matcher instrumented tests

- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/EqualToSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/Semver.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/EqualToSemverMatcherTest.java
- Added `EqualToSemver` matcher implementation.
> EqualToSemver matcher

- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/GreaterThanOrEqualToSemverMatcher.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/GreaterThanOrEqualToSemverMatcherTest.java
- Added `GreaterThanOrEqualToSemver` matcher implementation.
> GreaterThanOrEqualToSemver matcher

- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/LessThanOrEqualToSemverMatcher.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/LessThanOrEqualToSemverMatcherTest.java
- Added `LessThanOrEqualToSemver` matcher implementation.
> LessThanOrEqualToSemver matcher

- src/main/java/io/split/android/client/dtos/BetweenStringMatcherData.java
- src/main/java/io/split/android/client/dtos/Matcher.java
- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/BetweenSemverMatcher.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/BetweenSemverMatcherTest.java
- Added `BetweenSemver` matcher implementation.
> BetweenSemver matcher

- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/InListSemverMatcher.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/InListSemverMatcherTest.java
- Added `InListSemver` matcher implementation.
> InListSemver matcher

- src/main/java/io/split/android/client/dtos/BetweenStringMatcherData.java
- src/main/java/io/split/android/client/dtos/Matcher.java
- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/matchers/semver/BetweenSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/EqualToSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/GreaterThanOrEqualToSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/InListSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/LessThanOrEqualToSemverMatcher.java
- src/main/java/io/split/android/engine/matchers/semver/Semver.java
- src/test/java/io/split/android/engine/experiments/SplitParserTest.java
- src/test/java/io/split/android/engine/matchers/semver/BetweenSemverMatcherTest.java
- src/test/java/io/split/android/engine/matchers/semver/EqualToSemverMatcherTest.java
- src/test/java/io/split/android/engine/matchers/semver/GreaterThanOrEqualToSemverMatcherTest.java
- src/test/java/io/split/android/engine/matchers/semver/InListSemverMatcherTest.java
- src/test/java/io/split/android/engine/matchers/semver/LessThanOrEqualToSemverMatcherTest.java
- Semver matchers to baseline branch.
> Semver matchers

- src/androidTest/assets/split_changes_semver.json
- src/androidTest/java/helper/IntegrationHelper.java
- src/androidTest/java/tests/integration/matcher/SemverMatcherTest.java
- src/main/java/io/split/android/client/dtos/MatcherType.java
- Added instrumented tests for evaluations with semver matchers.
> Semver instrumented tests

- src/androidTest/assets/splitchanges_unsupported_matcher.json
- src/androidTest/java/tests/integration/matcher/UnsupportedMatcherTest.java
- src/main/java/io/split/android/client/TreatmentLabels.java
- src/main/java/io/split/android/client/dtos/MatcherType.java
- src/main/java/io/split/android/engine/experiments/DefaultConditionsProvider.java
- src/main/java/io/split/android/engine/experiments/SplitParser.java
- src/main/java/io/split/android/engine/experiments/UnsupportedMatcherException.java
- src/test/java/io/split/android/client/TreatmentLabelsTest.java
- src/test/java/io/split/android/engine/experiments/DefaultConditionsProviderTest.java
- src/test/java/io/split/android/engine/experiments/UnsupportedMatcherSplitParserTest.java
- Unsupported matchers baseline.
> Unsupported baseline
